name: release astra

on:
  push:
    tags:
      - v*

jobs:
  build-x8664:
    name: Build astra binary for Linux x8664
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - name: Set up Go 1.16.5
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5

      - name: Checkout astra code
        uses: actions/checkout@v2
        with:
          path: go/src/github.com/astra-net/go-sdk

      - name: Debug
        run: |
          pwd
          echo ${HOME}
          echo ${GITHUB_WORKSPACE}
          echo ${GOPATH}
          echo ${GOROOT}
        env:
          GOPATH: /home/runner/work/go-sdk/go-sdk/go

      - name: Checkout dependence repo
        uses: actions/checkout@v2
        with:
          repository: astra-net/mcl
          path: go/src/github.com/astra-net/mcl
        env:
          GOPATH: /home/runner/work/go-sdk/go-sdk/go

      - name: Checkout dependence repo
        uses: actions/checkout@v2
        with:
          repository: astra-net/bls
          path: go/src/github.com/astra-net/bls
        env:
          GOPATH: /home/runner/work/go-sdk/go-sdk/go

      - name: Checkout dependence code
        uses: actions/checkout@v2
        with:
          repository: astra-net/astra-network
          path: go/src/github.com/astra-net/astra-network
          ref: main
          fetch-depth: 0
        env:
          GOPATH: /home/runner/work/go-sdk/go-sdk/go

      - name: Get latest version and release
        run: |
          VERSION=$(git tag -l --sort=-v:refname | head -n 1 | tr -d v)
          RELEASE=$(git describe --long | cut -f2 -d-)
          echo "build_version=$VERSION" >> $GITHUB_ENV
          echo "build_release=$RELEASE" >> $GITHUB_ENV
        working-directory: /home/runner/work/go-sdk/go-sdk/go/src/github.com/astra-net/go-sdk
        env:
          GOPATH: /home/runner/work/go-sdk/go-sdk/go

      - name: Build astra binary for Linux
        if: matrix.os == 'ubuntu-18.04'
        run: |
          make static
        working-directory: /home/runner/work/go-sdk/go-sdk/go/src/github.com/astra-net/go-sdk
        env:
          GOPATH: /home/runner/work/go-sdk/go-sdk/go

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: astra
          path: /home/runner/work/go-sdk/go-sdk/go/src/github.com/astra-net/go-sdk/dist/*
          retention-days: 1
        env:
          GOPATH: /home/runner/work/go-sdk/go-sdk/go

  # build-arm64:
  #   name: Build astra binary
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ [ self-hosted,linux,ARM64 ] ]

  #   steps:

  #     - name: Set up Go 1.16.5
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.16.5

  #     - name: Checkout astra code
  #       uses: actions/checkout@v2
  #       with:
  #         path: go/src/github.com/astra-net/go-sdk

  #     - name: Debug
  #       run: |
  #         pwd
  #         echo ${HOME}
  #         echo ${GITHUB_WORKSPACE}
  #         echo ${GOPATH}
  #         echo ${GOROOT}
  #       env:
  #         GOPATH: /home/ubuntu/actions-runner/_work/go-sdk/go-sdk/go

  #     - name: Checkout dependence repo
  #       uses: actions/checkout@v2
  #       with:
  #         repository: astra-net/mcl
  #         path: go/src/github.com/astra-net/mcl
  #       env:
  #         GOPATH: /home/ubuntu/actions-runner/_work/go-sdk/go-sdk/go

  #     - name: Checkout dependence repo
  #       uses: actions/checkout@v2
  #       with:
  #         repository: astra-net/bls
  #         path: go/src/github.com/astra-net/bls
  #       env:
  #         GOPATH: /home/ubuntu/actions-runner/_work/go-sdk/go-sdk/go

  #     - name: Checkout dependence code
  #       uses: actions/checkout@v2
  #       with:
  #         repository: astra-net/astra-network
  #         path: go/src/github.com/astra-net/astra-network
  #         ref: main
  #         fetch-depth: 0
  #       env:
  #         GOPATH: /home/ubuntu/actions-runner/_work/go-sdk/go-sdk/go

  #     - name: Build astra binary for Arm
  #       run: |
  #         make static
  #         mv dist/astra dist/astra-arm64
  #         chmod +x dist/astra-arm64
  #       working-directory: /home/ubuntu/actions-runner/_work/go-sdk/go-sdk/go/src/github.com/astra-net/go-sdk
  #       env:
  #         GOPATH: /home/ubuntu/actions-runner/_work/go-sdk/go-sdk/go

  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: astra-arm64
  #         path: /home/ubuntu/actions-runner/_work/go-sdk/go-sdk/go/src/github.com/astra-net/go-sdk/dist/*
  #         retention-days: 1
  #       env:
  #         GOPATH: /home/ubuntu/actions-runner/_work/go-sdk/go-sdk/go

  release-page:
    name: Sign binary and create and publish release page
    needs: [build-x8664]
    runs-on: ubuntu-18.04

    steps:
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.ASTRA_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.ASTRA_GPG_PRIVATE_KEY_PASS }}

      - name: Checkout astra core code
        uses: actions/checkout@v2
        with:
          path: go/src/github.com/astra-net/go-sdk
        env:
          GOPATH: /home/runner/work/go-sdk/go-sdk/go

      - name: Get latest version
        run: |
          VERSION=$(git tag -l --sort=-v:refname | head -n 1 | tr -d v)
          VERSION_LONG=$(git describe --always --long --dirty)
          RELEASE=$(git describe --long | cut -f2 -d-)
          echo "build_version=$VERSION" >> $GITHUB_ENV
          echo "build_version_long=$VERSION_LONG" >> $GITHUB_ENV
          echo "build_release=$RELEASE" >> $GITHUB_ENV
        working-directory: /home/runner/work/go-sdk/go-sdk/go/src/github.com/astra-net/go-sdk
        env:
          GOPATH: /home/runner/work/go-sdk/go-sdk/go

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: astra

      - name: Signed amd64 astra binary
        run: |
          gpg --detach-sign astra
          sha256sum astra >> astra.sha256

      # - name: Download artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: astra-arm64

      # - name: Signed arm64 astra binary
      #   run: |
      #     gpg --detach-sign astra-arm64
      #     sha256sum astra-arm64 >> astra-arm64.sha256

      - name: Get tag message
        env:
          TAG_SHA: ${{ github.event.after }}
          GOPATH: /home/runner/work/go-sdk/go
        run: |
          touch ./tag_message.md
          echo -e "$TAG_SHA\n\nThe released version: $build_version_long" >> ./tag_message.md
        working-directory: /home/runner/work/go-sdk/go-sdk/go/src/github.com/astra-net/go-sdk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPATH: /home/runner/work/go-sdk/go-sdk/go
        with:
          tag_name: ${{ github.ref }}
          release_name: Mainnet Release ${{ env.build_version }}
          draft: true
          prerelease: false
          body_path: /home/runner/work/go-sdk/go-sdk/go/src/github.com/astra-net/go-sdk/tag_message.md

      - name: Upload astra binary for Linux (amd64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPATH: /home/runner/work/go-sdk/go-sdk/go
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./astra
          asset_name: astra
          asset_content_type: application/octet-stream

      - name: Upload sha256 signature of astra amd64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./astra.sha256
          asset_name: astra.sha256
          asset_content_type: text/plain

      - name: Upload gpg signature of astra amd64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./astra.sig
          asset_name: astra.sig
          asset_content_type: application/octet-stream

      # - name: Upload astra binary for ARM64
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GOPATH: /home/runner/work/go-sdk/go-sdk/go
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./astra-arm64
      #     asset_name: astra-arm64
      #     asset_content_type: application/octet-stream

      # - name: Upload sha256 signature of astra arm64 binary
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./astra-arm64.sha256
      #     asset_name: astra-arm64.sha256
      #     asset_content_type: text/plain

      # - name: Upload gpg signature of astra arm64 binary
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./astra-arm64.sig
      #     asset_name: astra-arm64.sig
      #     asset_content_type: application/octet-stream
